In [1]:
#basics
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#itertools
from itertools import product

# plotly and dash
import dash
from dash import dcc, html
import plotly.offline as pyo
import plotly.graph_objs as go
from dash.dependencies import Input, Output
from dash.exceptions import PreventUpdate
import plotly.express as px

#others
from pathlib import Path
import re

In [2]:
#this notebook is to make the dash plot for the production data and the world map
# I have called modules from the load clean production data and find load plot xy

In [3]:
import sys
sys.path.append("../src")   # VERY IMPORTANT

In [4]:
# load the production data 
from Load_clean_production_data import Load_clean_production_data

file_path = ("../../0_Volve_dataset/5_Production_data/Volve_production_data.xlsx")


production_df = Load_clean_production_data(file_path)

production_df

,DATEPRD,WELL_BORE_CODE,NPD_WELL_BORE_CODE,NPD_WELL_BORE_NAME,NPD_FIELD_CODE,NPD_FIELD_NAME,NPD_FACILITY_CODE,NPD_FACILITY_NAME,ON_STREAM_HRS,AVG_DOWNHOLE_PRESSURE,...,AVG_CHOKE_UOM,AVG_WHP_P,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL,FLOW_KIND,WELL_TYPE
0,2014-04-07,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,0.00000,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,WI
1,2014-04-08,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
2,2014-04-09,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
3,2014-04-10,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
4,2014-04-11,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,310.37614,...,%,33.09788,10.47992,33.07195,0.0,0.0,0.0,NaN,production,OP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15629,2016-09-14,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.07776,0.22879,0.01862,0.0,0.0,0.0,NaN,production,OP
15630,2016-09-15,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.08545,0.22914,0.00631,0.0,0.0,0.0,NaN,production,OP
15631,2016-09-16,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.08544,0.22896,0.01181,0.0,0.0,0.0,NaN,production,OP
15632,2016-09-17,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.07497,0.22846,0.02576,0.0,0.0,0.0,NaN,production,OP
15633,2016-09-18,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.0,injection,WI

In [5]:
# change the production_df from metric to field by changing the dataframe
# this only work on this particular production_df dataframe above
from Load_clean_production_data import metric_to_field
production_df_field=pd.DataFrame()
production_df_field=metric_to_field(production_df)
production_df_field

,DATEPRD,WELL_BORE_CODE,NPD_WELL_BORE_CODE,NPD_WELL_BORE_NAME,NPD_FIELD_CODE,NPD_FIELD_NAME,NPD_FACILITY_CODE,NPD_FACILITY_NAME,ON_STREAM_HRS,AVG_DOWNHOLE_PRESSURE_PSI,...,AVG_CHOKE_UOM,AVG_WHP_P_PSI,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL_STB,BORE_GAS_VOL_MSCF,BORE_WAT_VOL_STB,BORE_WI_VOL,FLOW_KIND,WELL_TYPE
0,2014-04-07,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,0.000000,...,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,NaN,production,WI
1,2014-04-08,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,NaN,production,OP
2,2014-04-09,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,NaN,production,OP
3,2014-04-10,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,NaN,production,OP
4,2014-04-11,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,4501.633459,...,%,480.045032,50.863856,33.07195,0.0,0.0,0.0,NaN,production,OP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15629,2016-09-14,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,1.127815,32.411822,0.01862,0.0,0.0,0.0,NaN,production,OP
15630,2016-09-15,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,1.239350,32.412452,0.00631,0.0,0.0,0.0,NaN,production,OP
15631,2016-09-16,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,1.239205,32.412128,0.01181,0.0,0.0,0.0,NaN,production,OP
15632,2016-09-17,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,1.087350,32.411228,0.02576,0.0,0.0,0.0,NaN,production,OP
15633,2016-09-18,NO 15/9-F-5 AH,5769,15/9-F-5,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.0,injection,WI

In [6]:
# load the XY coordinate data
from Find_Load_plot_X_Y_loc import Fetch_XY_location_make_dataframe
root_dir = Path("../../0_Volve_dataset/13_Well_technical_data")
df_headers=Fetch_XY_location_make_dataframe(root_dir)

In [7]:
# select the columns needed from the df_headers
df_XY=df_headers[['WELL NAME',
       'WELLBORE NAME', 'Surface EW', 'Surface NS', 'Surface Latitude',
       'Surface Longitude', 'Bottom Hole EW', 'Bottom Hole NS']]
df_XY

,WELL NAME,WELLBORE NAME,Surface EW,Surface NS,Surface Latitude,Surface Longitude,Bottom Hole EW,Bottom Hole NS
1,F-2,F-2,435047.604,6478564.735,58 26' 29.8447 N,1 53' 14.7783 E,435474.997,6479446.001
2,F-4,F-4,435049.831,6478560.825,58 26' 29.7195 N,1 53' 14.9196 E,435607.290,6477581.186
6,F-10,F-10,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,437989.579,6476538.580
9,F-10,NO 15/9-F-10,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,438039.045,6476491.728
11,F-10,F-10 A,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,435473.927,6479442.844
12,F-8,F-8,435050.021,6478563.523,58 26' 29.8068 N,1 53' 14.9285 E,434308.000,6476816.000
14,F-3,F-3,435048.718,6478562.780,58 26' 29.7821 N,1 53' 14.8489 E,435474.997,6479446.001
16,F-5,F-5,435050.945,6478558.870,58 26' 29.6569 N,1 53' 14.9902 E,436403.365,6478703.521
21,F-13,F-13,435051.324,6478564.265,58 26' 29.8315 N,1 53' 15.0081 E,436430.999,6478725.001
22,Relief well location 4,F-1 C,435030.000,6477220.000,58 25' 46.3658 N,1 53' 15.0647 E,434901.300,6478814.400
23,Relief well location 4,F-15 D,435030.000,6477220.000,58 25' 46.3658 N,1 53' 15.0647 E,435355.000,6479084.500
25,F-1,F-1 B,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,435450.817,6479291.192
30,F-1,F-1,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,434913.846,6479477.633
33,F-1,F-1 A,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,434592.072,6479461.861
41,F-11,15/9-F-11 T2,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,436161.108,6479140.849
46,F-11,15/9-F-11,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,435048.591,6478566.827
49,F-11,15/9-F-11 A,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,435347.126,6479269.323
55,F-11,15/9-F-11 B,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,436551.039,6478399.766
59,Relief well location 3,F-12,434552.000,6478471.000,58 26' 26.5485 N,1 52' 44.3204 E,435018.800,6478278.000
62,F-14,F-14,435052.438,6478562.310,58 26' 29.7689 N,1 53' 15.0788 E,436046.757,6478870.859
66,F-15,F-15A,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,433807.928,6478045.888
67,F-15,F-15C,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434791.854,6477854.380
71,F-15,F-15B,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434270.970,6477867.706
74,F-15,F-15,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434106.231,6476759.509
75,F-15,F-15D,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,436649.731,6478716.252
92,F-9,F-9 A,435051.135,6478561.568,58 26' 29.7442 N,1 53' 14.9992 E,434973.881,6478125.171
98,F-9,F-9,435051.135,6478561.568,58 26' 29.7442 N,1 53' 14.9992 E,435145.129,6478583.270
102,F-7,F-7,435048.907,6478565.478,58 26' 29.8694 N,1 53' 14.8578 E,434970.241,6478544.933

In [8]:
# changes the 'Surface Latitude','Surface Longitude' in degrees to  decimal and gives a new column lat_dd and lon_dd
from Find_Load_plot_X_Y_loc import dms_to_dd
from Find_Load_plot_X_Y_loc import DMS_decimal

df_XY=DMS_decimal(df_XY)
df_XY

,WELL NAME,WELLBORE NAME,Surface EW,Surface NS,Surface Latitude,Surface Longitude,Bottom Hole EW,Bottom Hole NS,lat_dd,lon_dd
1,F-2,F-2,435047.604,6478564.735,58 26' 29.8447 N,1 53' 14.7783 E,435474.997,6479446.001,58.441624,1.887438
2,F-4,F-4,435049.831,6478560.825,58 26' 29.7195 N,1 53' 14.9196 E,435607.290,6477581.186,58.441589,1.887478
6,F-10,F-10,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,437989.579,6476538.580,58.441578,1.887519
9,F-10,NO 15/9-F-10,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,438039.045,6476491.728,58.441578,1.887519
11,F-10,F-10 A,435052.248,6478559.613,58 26' 29.6816 N,1 53' 15.0698 E,435473.927,6479442.844,58.441578,1.887519
12,F-8,F-8,435050.021,6478563.523,58 26' 29.8068 N,1 53' 14.9285 E,434308.000,6476816.000,58.441613,1.887480
14,F-3,F-3,435048.718,6478562.780,58 26' 29.7821 N,1 53' 14.8489 E,435474.997,6479446.001,58.441606,1.887458
16,F-5,F-5,435050.945,6478558.870,58 26' 29.6569 N,1 53' 14.9902 E,436403.365,6478703.521,58.441571,1.887497
21,F-13,F-13,435051.324,6478564.265,58 26' 29.8315 N,1 53' 15.0081 E,436430.999,6478725.001,58.441620,1.887502
22,Relief well location 4,F-1 C,435030.000,6477220.000,58 25' 46.3658 N,1 53' 15.0647 E,434901.300,6478814.400,58.429546,1.887518
23,Relief well location 4,F-15 D,435030.000,6477220.000,58 25' 46.3658 N,1 53' 15.0647 E,435355.000,6479084.500,58.429546,1.887518
25,F-1,F-1 B,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,435450.817,6479291.192,58.441641,1.887419
30,F-1,F-1,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,434913.846,6479477.633,58.441641,1.887419
33,F-1,F-1 A,435046.488,6478566.687,58 26' 29.9072 N,1 53' 14.7075 E,434592.072,6479461.861,58.441641,1.887419
41,F-11,15/9-F-11 T2,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,436161.108,6479140.849,58.441655,1.887463
46,F-11,15/9-F-11,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,435048.591,6478566.827,58.441655,1.887463
49,F-11,15/9-F-11 A,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,435347.126,6479269.323,58.441655,1.887463
55,F-11,15/9-F-11 B,435049.095,6478568.172,58 26' 29.9566 N,1 53' 14.8667 E,436551.039,6478399.766,58.441655,1.887463
59,Relief well location 3,F-12,434552.000,6478471.000,58 26' 26.5485 N,1 52' 44.3204 E,435018.800,6478278.000,58.440708,1.878978
62,F-14,F-14,435052.438,6478562.310,58 26' 29.7689 N,1 53' 15.0788 E,436046.757,6478870.859,58.441602,1.887522
66,F-15,F-15A,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,433807.928,6478045.888,58.441585,1.887541
67,F-15,F-15C,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434791.854,6477854.380,58.441585,1.887541
71,F-15,F-15B,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434270.970,6477867.706,58.441585,1.887541
74,F-15,F-15,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,434106.231,6476759.509,58.441585,1.887541
75,F-15,F-15D,435053.552,6478560.355,58 26' 29.7063 N,1 53' 15.1494 E,436649.731,6478716.252,58.441585,1.887541
92,F-9,F-9 A,435051.135,6478561.568,58 26' 29.7442 N,1 53' 14.9992 E,434973.881,6478125.171,58.441596,1.887500
98,F-9,F-9,435051.135,6478561.568,58 26' 29.7442 N,1 53' 14.9992 E,435145.129,6478583.270,58.441596,1.887500
102,F-7,F-7,435048.907,6478565.478,58 26' 29.8694 N,1 53' 14.8578 E,434970.241,6478544.933,58.441630,1.887460

In [9]:
production_df_field = production_df_field.drop(columns=[
    col for col in [
        "WELL_BORE_CODE",
        "NPD_WELL_BORE_CODE",
       "NPD_FIELD_CODE",
       "ON_STREAM_HRS",
        "NPD_FIELD_NAME",
        "NPD_FACILITY_CODE",
        "NPD_FACILITY_NAME",
        "NPD_FIELD_CODE",
        'BORE_WI_VOL', 
        'FLOW_KIND',
        'WELL_TYPE'
        ] if col in production_df_field.columns
    ])

production_df_field

,DATEPRD,NPD_WELL_BORE_NAME,AVG_DOWNHOLE_PRESSURE_PSI,AVG_DOWNHOLE_TEMPERATURE_F,AVG_DP_TUBING_PSI,AVG_ANNULUS_PRESS_PSI,AVG_CHOKE_SIZE_P,AVG_CHOKE_UOM,AVG_WHP_P_PSI,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL_STB,BORE_GAS_VOL_MSCF,BORE_WAT_VOL_STB
0,2014-04-07,15/9-F-1 C,0.000000,32.000000,0.000000,0.000000,0.000000,%,0.000000,32.000000,0.00000,0.0,0.0,0.0
1,2014-04-08,15/9-F-1 C,NaN,NaN,NaN,0.000000,1.003059,%,0.000000,32.000000,0.00000,0.0,0.0,0.0
2,2014-04-09,15/9-F-1 C,NaN,NaN,NaN,0.000000,0.979008,%,0.000000,32.000000,0.00000,0.0,0.0,0.0
3,2014-04-10,15/9-F-1 C,NaN,NaN,NaN,0.000000,0.545759,%,0.000000,32.000000,0.00000,0.0,0.0,0.0
4,2014-04-11,15/9-F-1 C,4501.633459,206.376602,4021.588427,0.000000,1.215987,%,480.045032,50.863856,33.07195,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15629,2016-09-14,15/9-F-5,NaN,NaN,NaN,3.955476,0.636088,%,1.127815,32.411822,0.01862,0.0,0.0,0.0
15630,2016-09-15,15/9-F-5,NaN,NaN,NaN,4.160560,0.670794,%,1.239350,32.412452,0.00631,0.0,0.0,0.0
15631,2016-09-16,15/9-F-5,NaN,NaN,NaN,4.148667,0.664393,%,1.239205,32.412128,0.01181,0.0,0.0,0.0
15632,2016-09-17,15/9-F-5,NaN,NaN,NaN,3.946774,0.624660,%,1.087350,32.411228,0.02576,0.0,0.0,0.0
15633,2016-09-18,15/9-F-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN

In [10]:
# manually add the coordinates from the xy table to the production data
production_df_field["lat_dd"]=None
production_df_field["lon_dd"]=None

production_df_field.loc[production_df['NPD_WELL_BORE_NAME'] == '15/9-F-1 C', 'lat_dd'] = 58.429546
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-1 C', 'lon_dd'] = 1.887518

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-11', 'lat_dd'] = 58.441655
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-11', 'lon_dd'] = 1.887463

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-12', 'lat_dd'] = 58.440708	
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-12', 'lon_dd'] = 1.878978

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-14', 'lat_dd'] = 58.441602	
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-14', 'lon_dd'] = 1.887522

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-15 D', 'lat_dd'] = 58.441585	
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-15 D', 'lon_dd'] = 1.887541

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-4', 'lat_dd'] = 58.441589	
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-4', 'lon_dd'] = 1.887478

production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-5', 'lat_dd'] = 58.441571	
production_df_field.loc[production_df_field['NPD_WELL_BORE_NAME'] == '15/9-F-5', 'lon_dd'] = 1.887497

In [11]:
production_df_field

,DATEPRD,NPD_WELL_BORE_NAME,AVG_DOWNHOLE_PRESSURE_PSI,AVG_DOWNHOLE_TEMPERATURE_F,AVG_DP_TUBING_PSI,AVG_ANNULUS_PRESS_PSI,AVG_CHOKE_SIZE_P,AVG_CHOKE_UOM,AVG_WHP_P_PSI,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL_STB,BORE_GAS_VOL_MSCF,BORE_WAT_VOL_STB,lat_dd,lon_dd
0,2014-04-07,15/9-F-1 C,0.000000,32.000000,0.000000,0.000000,0.000000,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,58.429546,1.887518
1,2014-04-08,15/9-F-1 C,NaN,NaN,NaN,0.000000,1.003059,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,58.429546,1.887518
2,2014-04-09,15/9-F-1 C,NaN,NaN,NaN,0.000000,0.979008,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,58.429546,1.887518
3,2014-04-10,15/9-F-1 C,NaN,NaN,NaN,0.000000,0.545759,%,0.000000,32.000000,0.00000,0.0,0.0,0.0,58.429546,1.887518
4,2014-04-11,15/9-F-1 C,4501.633459,206.376602,4021.588427,0.000000,1.215987,%,480.045032,50.863856,33.07195,0.0,0.0,0.0,58.429546,1.887518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15629,2016-09-14,15/9-F-5,NaN,NaN,NaN,3.955476,0.636088,%,1.127815,32.411822,0.01862,0.0,0.0,0.0,58.441571,1.887497
15630,2016-09-15,15/9-F-5,NaN,NaN,NaN,4.160560,0.670794,%,1.239350,32.412452,0.00631,0.0,0.0,0.0,58.441571,1.887497
15631,2016-09-16,15/9-F-5,NaN,NaN,NaN,4.148667,0.664393,%,1.239205,32.412128,0.01181,0.0,0.0,0.0,58.441571,1.887497
15632,2016-09-17,15/9-F-5,NaN,NaN,NaN,3.946774,0.624660,%,1.087350,32.411228,0.02576,0.0,0.0,0.0,58.441571,1.887497
15633,2016-09-18,15/9-F-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,58.441571,1.887497

In [12]:
# fetch the polygon and make it into a dataframe
from Find_Load_plot_X_Y_loc import poly
file_path = Path("../../0_Volve_dataset/2_Geophysical_Interpretations/Fault_polygons/2014_Volve_Hugin_Base.dat")
df_poly=poly(file_path)
df_poly

     polygon_id  point_order          x          y            z
0            71            1  435259.53  6479503.5  2714.235352
1            71            2  435219.94  6479501.0  2706.789307
2            71            3  435181.06  6479502.0  2710.512207
3            71            4  435163.38  6479498.5  2712.498047
4            71            5  435115.31  6479473.0  2708.030273
...         ...          ...        ...        ...          ...
1495          0            8  436859.97  6479294.0  2804.401123
1496          0            9  436772.91  6479190.0  2807.272949
1497          0           10  436700.34  6479132.0  2805.930420
1498          0           11  436668.19  6479116.5  2756.585205
1499          0           12  436678.56  6479149.0  2803.462647

[1500 rows x 5 columns]

In [13]:
app=dash.Dash()
fig_wells = px.scatter_geo(production_df_field,lat="lat_dd",lon="lon_dd",hover_name="NPD_WELL_BORE_NAME")
app.layout=html.Div([
                    # basic header
                     html.Div([html.H1('Production DashBoard')],style={"border": "1px solid black","height": "8vh","textAlign": "center"}),   
                     # Dropdown
    
                     # Production plot and xy_map div
                     html.Div([
                             # Production plot
                             html.Div([
                                      dcc.Graph(
                                                id="Production_plot",
                                               style={"width": "100%", "height": "100%"}  # this style is for the graph itself
                                               )
                                        ],style={"border": "1px solid gray", "width": "60%", "height": "60vh" }), # this style is for layout of the div
            
                             # map plot
                             html.Div([
                                      dcc.Graph(id="xy_map",
                                                figure={"data":fig_wells.data,                                                      # the px.scatter_geo(...) already returns a complete Plotly Figure so use.data to return data
                                                      "layout":go.Layout(title={"text": "Map View", "x": 0.5, "xanchor": "center","y": 0.9,"yanchor": "top","font": {"size": 40}}, 
                                                                         hovermode ="closest",  
                                                                         margin={"l": 0, "r": 0, "t": 10, "b": 0}
                                                                        )
                                                       },
                                                style={"width": "100%", "height": "100%"} # this style is for the graph itself
                                               )
                                     ],style={"border": "1px solid gray", "width": "40%", "height": "60vh"}),  
                         
                     ],style={"border": "1px solid gray", "display": "flex","width": "100vw","height": "60vh"}), # this style is for the production plot and xy_map together
    
                    # div for all output and gauges
                    html.Div([
                            # Gauge
                             html.Div([
                                     html.Div(
                                              dcc.Graph(
                                                       id="Oil_gauge",
                                                       style={"width": "100%", "height": "100%"}
                                                       ),             
                                              style={"border": "1px solid lightgray", "width": "33.33%", "height": "30vh"}
                                             ),
                                     html.Div(
                                            dcc.Graph(
                                                     id="Gas_gauge",
                                                     style={"width": "100%", "height": "100%"}
                                                     ),
                                            style={"border": "1px solid lightgray", "width": "33.33%", "height": "30vh"}                                 
                                             ),
                                    html.Div(
                                            dcc.Graph(
                                                     id="Water_gauge",
                                                     style={"width": "100%", "height": "100%"}
                                                    ),         
                                           style={"border": "1px solid lightgray", "width": "33.33%", "height": "30vh"})
                                     ],
                                         
                                   style={"border": "1px solid gray", "width": "60%", "height": "30vh", 'display': 'flex', 'flex-direction': 'row'}),
        
                            # div for all outputs
                             html.Div([
                                         #oil
                                    html.Div(id="oil_text_output",style={"marginBottom": "25px"}),
                                    html.Div(id="gas_text_output",style={"marginBottom": "25px"}),
                                    html.Div(id="water_text_output",style={"marginBottom": "25px"}),
                                    html.Div(id="whp_text_output"),
                                      ],style={"border": "1px solid gray", "width": "40%", "height": "30vh", 'display': 'flex', 'flex-direction': 'column',"fontSize": "50px","fontWeight": "bold","padding": "35x"})
                                     

                        
                                      ],style={"display": "flex","flexDirection": "row","width": "100vw","height": "30vh"})   
                     
    
    
    

    
                    ],style={"border": "1px solid gray", "width": "100vw", "height": "100vh"})


#--------------------------------------------------------------------------------------------------------------------
# start of making the production plots
#---------------------------------------------------------------------------------------------------------------------
@app.callback(Output("Production_plot", "figure"),
              [Input("xy_map", "selectedData")])
def plot_production(selectedData):
    
    if not selectedData or not selectedData.get("points"):
        return go.Figure()
    #print(selectedData)

    wells = [p["hovertext"] for p in selectedData["points"]]
    #print(wells)
    
    #data = []

    for well in wells:
        filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]

        # make traces for oil gas and water
        trace_oil =go.Scatter(x=filter_df_well["DATEPRD"],y=filter_df_well['BORE_OIL_VOL_STB'], mode = "lines", name= "Oil Rate", line={"color":"green"},yaxis="y2")
        trace_gas =go.Scatter(x=filter_df_well["DATEPRD"],y=filter_df_well['BORE_GAS_VOL_MSCF'], mode = "lines", name= "Gas Rate", line_color="Red")
        trace_water =go.Scatter(x=filter_df_well["DATEPRD"],y=filter_df_well['BORE_WAT_VOL_STB'], mode = "lines", name= "Water Rate" ,line={"color":"blue"},yaxis="y2")
        trace_whp =go.Scatter(x=filter_df_well["DATEPRD"],y=filter_df_well['AVG_WHP_P_PSI'], mode = "lines", name= "WHP" ,line={"color":"purple"},yaxis="y2")

        data=[trace_oil,trace_gas,trace_water,trace_whp]

        layout = go.Layout(
                    title = {"text": f"Wellname<br>{well}", "font": {"size": 22}},
                    xaxis = {"title": {"text": "Time (days)", "font": {"color": "black","size": 36}},"tickfont": {"size": 22, "color": "black"}},
                    yaxis=  {"title": {"text": "Gas Rate (mscf)", "font": {"color": "Red","size": 36}},"tickfont": {"size": 22, "color": "black"}},
                    yaxis2={"title": {"text": '<span style="color:green">Oil Rate (stb)</span><br>'
                                              '<span style="color:blue">Water Rate (stb)</span><br>'
                                              '<span style="color:purple">WHP (psi)</span>', 
                                      "font": {"color": "black","size": 36}}, 
                            "tickfont":{"color":"black", "size":22},  
                            "overlaying":"y",
                            "side":"right"},
                    legend = {"x":1.07, "y":1,"font": {"size": 24}},
                    autosize=True,
        
                    hovermode = "closest"
                    )
        #fig = go.Figure(data=data)
        #fig.update_xaxes(rangeslider_visible=True, type="date")
        fig =go.Figure(data=data, layout=layout)
        fig.update_xaxes(rangeslider_visible=True,type="date")

        return fig
#--------------------------------------------------------------------------------------------------------------------
# start of the gauges
#---------------------------------------------------------------------------------------------------------------------
# Oil gague   
@app.callback(Output("Oil_gauge", "figure"),
              [Input("xy_map", "selectedData")])
def Oil_gauge(selectedData):
    if not selectedData or not selectedData.get("points"):
        return go.Figure()
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate value for gauge
    total_oil = filter_df_well["BORE_OIL_VOL_STB"].sum()
    #print(total_oil)

    max_oil = production_df_field.groupby("NPD_WELL_BORE_NAME")["BORE_OIL_VOL_STB"].sum().max()
    fig = go.Figure(go.Indicator(
        domain = {'x': [0, 1], 'y': [0, 1]},
        mode="gauge+number",
        value=total_oil,
        title={"text": f"Total Oil Volume<br>{well}", "font": {"size": 32}},
        gauge={
            "axis": {"range": [None, max_oil * 1.1], "tickfont": {"size": 22}},
            "bar": {"color": "gray"},
            "steps": [
                {"range": [0, max_oil * 0.33], "color": "red"},
                {"range": [max_oil * 0.33, max_oil * 0.66], "color": "yellow"},
                {"range": [max_oil * 0.66, max_oil], "color": "green"},
                     ],
           'threshold' : {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': max_oil*1.05}
        }
    ))
    return fig
    
# Gas gague 
@app.callback(Output("Gas_gauge", "figure"),
              [Input("xy_map", "selectedData")])
def Gas_gauge(selectedData):
    if not selectedData or not selectedData.get("points"):
        return go.Figure()
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate value for gauge
    total_gas = filter_df_well["BORE_GAS_VOL_MSCF"].sum()
    #print(total_gas)

    max_gas = production_df_field.groupby("NPD_WELL_BORE_NAME")["BORE_GAS_VOL_MSCF"].sum().max()
    fig = go.Figure(go.Indicator(
        domain = {'x': [0, 1], 'y': [0, 1]},
        mode="gauge+number",
        value=total_gas,
        title={"text": f"Total Gas Volume<br>{well}","font": {"size": 32}},
        gauge={
            "axis": {"range": [None, max_gas * 1.0],"tickfont": {"size": 22}},
            "bar": {"color": "gray"},
            "steps": [
                {"range": [0, max_gas * 0.33], "color": "red"},
                {"range": [max_gas * 0.33, max_gas * 0.66], "color": "yellow"},
                {"range": [max_gas * 0.66, max_gas], "color": "green"},
                     ],
           'threshold' : {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': max_gas*1.0}
        }
    ))
    return fig

# Water gague 
@app.callback(Output("Water_gauge", "figure"),
              [Input("xy_map", "selectedData")])
def Water_gauge(selectedData):
    if not selectedData or not selectedData.get("points"):
        return go.Figure()
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate value for gauge
    total_water = filter_df_well["BORE_WAT_VOL_STB"].sum()
    #print(total_water)

    max_water = production_df_field.groupby("NPD_WELL_BORE_NAME")["BORE_WAT_VOL_STB"].sum().max()
    fig = go.Figure(go.Indicator(
        domain = {'x': [0, 1], 'y': [0, 1]},
        mode="gauge+number",
        value=total_water,
        title={"text": f"Total Water Volume<br>{well}","font": {"size": 32}},
        gauge={
            "axis": {"range": [None, max_water * 1.2],"tickfont": {"size": 22}},
            "bar": {"color": "gray"},
            "steps": [
                {"range": [0, max_water * 0.33], "color": "green"},
                {"range": [max_water * 0.33, max_water * 0.66], "color": "yellow"},
                {"range": [max_water * 0.66, max_water], "color": "red"},
                     ],
           'threshold' : {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': 5E6}
        }
    ))
    return fig

#--------------------------------------------------------------------------------------------------------------------
# start of the Output text
#---------------------------------------------------------------------------------------------------------------------
# Oil output text
@app.callback(Output("oil_text_output", "children"),
              [Input("xy_map", "selectedData")])
def Oil_text(selectedData):
    if selectedData is None or len(selectedData["points"]) == 0:
        return ""
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate the last 30 days
    last_oil = filter_df_well["BORE_OIL_VOL_STB"].tail(30).fillna(0).mean()
    return f"Last 30 day Average Oil Production: {last_oil:.0f} stb"

# Gas output text
@app.callback(Output("gas_text_output", "children"),
              [Input("xy_map", "selectedData")])
def Gas_text(selectedData):
    if selectedData is None or len(selectedData["points"]) == 0:
        return ""
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate the last 30 days
    last_gas = filter_df_well["BORE_GAS_VOL_MSCF"].tail(30).fillna(0).mean()
    return f"Last 30 day Average Gas Production: {last_gas:.0f} Mscf"

# Water output text
@app.callback(Output("water_text_output", "children"),
              [Input("xy_map", "selectedData")])
def Water_text(selectedData):
    if selectedData is None or len(selectedData["points"]) == 0:
        return ""
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate the last 30 days
    last_water = filter_df_well["BORE_WAT_VOL_STB"].tail(30).fillna(0).mean()
    return f"Last 30 day Average Water Production: {last_water:.0f} stb"

# WHP output text
@app.callback(Output("whp_text_output", "children"),
              [Input("xy_map", "selectedData")])
def WHP_text(selectedData):
    if selectedData is None or len(selectedData["points"]) == 0:
        return ""
    # get selected well name
    well = selectedData["points"][0]["hovertext"]
    
    # filter production data for that well
    filter_df_well = production_df_field[production_df_field["NPD_WELL_BORE_NAME"] == well]
    # calculate the last 30 days
    last_whp = filter_df_well["AVG_WHP_P_PSI"].tail(30).fillna(0).mean()
    return f"Last 30 day Average Wellhead Pressure: {last_whp:.0f} psi"

        


if __name__ == '__main__':
    app.run()